### PR TITLE
Merged with more details logic from https://github.com/Nilsty/whoami

### PR DESCRIPTION
**Pull request by olljanat**
I noticed that http.go version on https://github.com/Nilsty/whoami contains much more details which are useful on debugging but that version misses Windows support so I merged those together on this.

### CODE REVIEW

**Comment by StefanScherer** [comment]
@olljanat that looks promising. Thanks so far. I saw the build error on Windows, but hadn't the time to look closer. I kicked off CI again, but it failed again.
Maybe related to the latest Windows update problem we saw in moby/moby this week. https://github.com/moby/moby/pull/40512

**Comment by olljanat** [comment]
@StefanScherer That is good to know. It really looks like Windows/AppVeyor specific issue.

And yes those modifications looks very useful. I already find out that Traefik 2.x removes all X-Forwarded-? headers ( https://github.com/containous/traefik/blob/a20a6636b4582e4e7b562fc01f64567775fc8a9a/pkg/middlewares/forwardedheaders/forwarded_header.go#L40-L42 ) if forwardedHeaders.insecure is not specified ( https://docs.traefik.io/v2.0/routing/entrypoints/#forwarded-header ) so it would be very nice to have Windows version with headers printout available before I start trying to port those to use Traefik 2.x.

**Comment by StefanScherer** [comment]
I looked into what might be the problem. Oh it's just the message `Starting up on port 8080` that is written to stderr. When we run `docker logs whoamitest` this message then also gets written to stderr, this is an indicator for PowerShell to abort the execution.

I would suggest to just swap the lines 17 and 19, to ignore such "error" during the `docker logs` command. @olljanat could you update your PR, to see if it's green afterwards?

**Review by StefanScherer — APPROVED** [review]
Yes, it's green!

LGTM 🎉

**Comment by olljanat** [comment]
Looks that deploy failed to NPM error from rebase-docker-image:
```
Rebasing image to produce 2016/1607 variant
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by StefanScherer** [comment]
Correct, I tried to update npm dependencies, but the `request` package is deprecated, also the latest 2.88.2. 
So, my quick fix is to suppress PowerShell errors due to that warning. I've kicked CI again.

**Comment by StefanScherer** [comment]
@olljanat It took a little longer, but finally CI has uploaded a new image to Docker Hub. It turns out that the rebase-docker-image tool had problems with the new base images from MCR. It reads the  manifest JSON case-sensitive and they now use `rootfS` with an upper-case `S` instead of `rootfs` 🤔

**Pull request merged**
